#!/usr/bin/env python3
"""Bake raster transforms for native Windows printing, using checked anchors.

Run after the existing .patch files and 005-barcode-text-gui.py:
    python patches/006-fix-windows-raster-printing.py src
Use --check to validate all anchors without writing. Re-running is safe.
Validated against upstream 554c9f04389f7a1afa18685cab015273f0b21d94.
"""
import argparse
import re
from pathlib import Path

HEADER = r"""// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by 006-fix-windows-raster-printing.py. Remove when the native
// Windows raster printing path reliably handles arbitrary image transforms.
#pragma once

#include <QDebug>
#include <QImage>
#include <QPaintEngine>
#include <QPainter>
#include <QTransform>
#include <algorithm>
#include <cmath>

namespace glabels::model::detail
{
    inline void drawWindowsRasterImage( QPainter* painter, const QRectF& destRect,
                                        const QImage& image, bool inEditor )
    {
        // Preview uses Raster/Picture; PDF uses Pdf. Only native Windows
        // printing reaches this branch, including Windows virtual printers.
        if ( inEditor || !painter->paintEngine() ||
             painter->paintEngine()->type() != QPaintEngine::Windows )
        {
            painter->drawImage( destRect, image );
            return;
        }
        if ( image.isNull() || destRect.isEmpty() )
        {
            return;
        }

        // Include object, label/page rotation, reverse printing, printer DPI
        // and device offsets. A determinant test alone misses 180-degree turns.
        const QTransform deviceMap = painter->deviceTransform();
        const QRectF mapped = deviceMap.mapRect( destRect );
        if ( !deviceMap.isAffine() || !deviceMap.isInvertible() ||
             !std::isfinite( mapped.left() ) || !std::isfinite( mapped.top() ) ||
             !std::isfinite( mapped.right() ) || !std::isfinite( mapped.bottom() ) )
        {
            qWarning( "006: invalid raster print transform; image skipped" );
            return;
        }

        // Intersect in floating point before converting to integers. Limit
        // work to the printable page and the current label's clip bounds.
        QRectF visible = mapped.intersected( QRectF( 0, 0,
            painter->device()->width(), painter->device()->height() ) );
        if ( painter->hasClipping() )
        {
            visible = visible.intersected(
                deviceMap.mapRect( painter->clipBoundingRect() ) );
        }
        const QRect bounds = visible.toAlignedRect();
        if ( bounds.isEmpty() )
        {
            return;
        }

        painter->save();
        // Keep the window/viewport mapping: resetTransform() would also reset
        // it and can change a clip established before that view mapping.
        painter->setWorldTransform( QTransform() );
        bool invertible = false;
        const QTransform baseInverse = painter->deviceTransform().inverted( &invertible );
        if ( !invertible )
        {
            painter->restore();
            qWarning( "006: invalid printer device transform; image skipped" );
            return;
        }
        painter->setWorldTransform( baseInverse );

        // Keep temporary memory bounded (~4 MiB per tile), even at 1200 DPI.
        // The original printer clip, opacity and composition remain active.
        constexpr int tileSize = 1024;
        for ( int y = bounds.top(); y < bounds.top() + bounds.height(); y += tileSize )
        {
            for ( int x = bounds.left(); x < bounds.left() + bounds.width(); x += tileSize )
            {
                const int w = std::min( tileSize, bounds.left() + bounds.width() - x );
                const int h = std::min( tileSize, bounds.top() + bounds.height() - y );
                QImage tile( w, h, QImage::Format_ARGB32_Premultiplied );
                if ( tile.isNull() )
                {
                    painter->restore();
                    qWarning( "006: cannot allocate raster print tile" );
                    return;
                }
                tile.fill( Qt::transparent );
                {
                    QPainter raster( &tile );
                    raster.setRenderHints( painter->renderHints() );
                    raster.setWorldTransform( deviceMap * QTransform::fromTranslate( -x, -y ) );
                    raster.drawImage( destRect, image );
                }
                // The Windows driver receives device-aligned, already oriented
                // pixels: no rotation, reflection or shear remains to interpret.
                painter->drawImage( QRectF( x, y, w, h ), tile );
            }
        }
        painter->restore();
    }
}
"""
TEST = r"""// SPDX-License-Identifier: GPL-3.0-or-later
#include "model/WindowsRasterPrint.hpp"
#include <QCoreApplication>
#include <QPainterPath>
#include <QPixmap>
#include <iostream>

// Capture what the native engine receives, then paint it into an ordinary
// QImage. No hardware or printer driver is required for these regressions.
class CaptureEngine : public QPaintEngine
{
public:
    QImage result;
    QPainter output;
    QTransform transform;
    QPainterPath clip;
    bool clipping = false;
    qreal opacity = 1;
    QPainter::CompositionMode composition = QPainter::CompositionMode_SourceOver;
    QPainter::RenderHints hints;
    Type kind;
    int calls = 0;
    bool deviceAligned = true;
    int maxTilePixels = 0;

    CaptureEngine( Type type, QSize size ) : QPaintEngine( AllFeatures ),
        result( size, QImage::Format_ARGB32_Premultiplied ), kind( type )
    {
        result.fill( Qt::white );
    }
    bool begin( QPaintDevice* ) override { return output.begin( &result ); }
    bool end() override { return output.end(); }
    Type type() const override { return kind; }
    void updateState( const QPaintEngineState& state ) override
    {
        if ( state.state() & DirtyTransform ) transform = state.transform();
        if ( state.state() & DirtyOpacity ) opacity = state.opacity();
        if ( state.state() & DirtyCompositionMode ) composition = state.compositionMode();
        if ( state.state() & DirtyHints ) hints = state.renderHints();
        if ( state.state() & DirtyClipPath )
        {
            const auto path = state.transform().map( state.clipPath() );
            if ( state.clipOperation() == Qt::IntersectClip && !clip.isEmpty() )
                clip = clip.intersected( path );
            else clip = path;
        }
        if ( state.state() & DirtyClipRegion )
        {
            QPainterPath path;
            for ( const QRect& rect : state.clipRegion() ) path.addRect( rect );
            path = state.transform().map( path );
            if ( state.clipOperation() == Qt::IntersectClip && !clip.isEmpty() )
                clip = clip.intersected( path );
            else clip = path;
        }
        if ( state.state() & DirtyClipEnabled ) clipping = state.isClipEnabled();
    }
    void drawImage( const QRectF& rect, const QImage& image,
                    const QRectF& source, Qt::ImageConversionFlags flags ) override
    {
        ++calls;
        deviceAligned = deviceAligned && transform.isIdentity();
        maxTilePixels = std::max( maxTilePixels, image.width() * image.height() );
        output.save();
        output.resetTransform();
        if ( clipping ) output.setClipPath( clip );
        output.setTransform( transform );
        output.setOpacity( opacity );
        output.setCompositionMode( composition );
        output.setRenderHints( hints );
        output.drawImage( rect, image, source, flags );
        output.restore();
    }
    void drawPixmap( const QRectF& rect, const QPixmap& pixmap, const QRectF& source ) override
    { drawImage( rect, pixmap.toImage(), source, Qt::AutoColor ); }
};

class CaptureDevice : public QPaintDevice
{
public:
    mutable CaptureEngine engine;
    CaptureDevice( QPaintEngine::Type type, QSize size ) : engine( type, size ) {}
    QPaintEngine* paintEngine() const override { return &engine; }
    int metric( PaintDeviceMetric metric ) const override
    {
        switch ( metric )
        {
        case PdmWidth: return engine.result.width();
        case PdmHeight: return engine.result.height();
        case PdmWidthMM: return engine.result.width() * 254 / 960;
        case PdmHeightMM: return engine.result.height() * 254 / 960;
        case PdmDpiX: case PdmDpiY: case PdmPhysicalDpiX: case PdmPhysicalDpiY: return 96;
        case PdmDepth: return 32;
        case PdmNumColors: return 0;
        case PdmDevicePixelRatio: return 1;
        case PdmDevicePixelRatioScaled: return int( devicePixelRatioFScale() );
        default: return QPaintDevice::metric( metric );
        }
    }
};

static int failures = 0;
static void check( bool condition, const char* name )
{
    if ( !condition ) { ++failures; std::cerr << "FAIL: " << name << '\n'; }
}

static void runCase( const char* name, const QTransform& map, QSize size,
                     bool clip, qreal opacity, bool view, bool smooth,
                     QPaintEngine::Type type = QPaintEngine::Windows, bool editor = false,
                     int tolerance = 0 )
{
    QImage source( 17, 11, QImage::Format_ARGB32_Premultiplied );
    source.fill( Qt::transparent );
    // Unequal dimensions and asymmetric colored blocks expose every flip/turn.
    for ( int y = 0; y < source.height(); ++y )
        for ( int x = 0; x < source.width(); ++x )
            source.setPixelColor( x, y, QColor( (x*13)%256, (y*23)%256,
                (x*7+y*11)%256, (x+y)%4 ? 255 : 96 ) );
    const QRectF rect( 3, 5, 119, 77 );
    QPainterPath clipPath;
    clipPath.addEllipse( QRectF( 20, 20, size.width()-40, size.height()-40 ) );
    QImage expected( size, QImage::Format_ARGB32_Premultiplied );
    expected.fill( Qt::white );
    CaptureDevice device( type, size );
    {
        QPainter reference( &expected );
        QPainter actual( &device );
        for ( QPainter* p : { &reference, &actual } )
        {
            p->setClipPath( clipPath );
            p->setClipping( clip );
            p->setOpacity( opacity );
            p->setRenderHint( QPainter::SmoothPixmapTransform, smooth );
            if ( view )
            {
                p->setWindow( 0, 0, size.width(), size.height() );
                p->setViewport( 11, 7, size.width()*2, size.height()*2 );
            }
            p->setTransform( map );
        }
        const auto before = actual.deviceTransform();
        const auto clipBefore = actual.clipPath();
        reference.drawImage( rect, source );
        glabels::model::detail::drawWindowsRasterImage( &actual, rect, source, editor );
        check( actual.deviceTransform() == before, "painter transform restored" );
        check( actual.clipPath() == clipBefore && actual.hasClipping() == clip,
               "painter clip restored" );
        check( actual.opacity() == opacity, "painter opacity restored" );
    }
    int different = 0;
    int maxDifference = 0;
    for ( int y = 0; y < size.height(); ++y )
        for ( int x = 0; x < size.width(); ++x )
        {
            const QColor a = expected.pixelColor( x, y );
            const QColor b = device.engine.result.pixelColor( x, y );
            const int delta = std::max( { std::abs(a.red()-b.red()),
                std::abs(a.green()-b.green()), std::abs(a.blue()-b.blue()),
                std::abs(a.alpha()-b.alpha()) } );
            maxDifference = std::max( maxDifference, delta );
            // Pre-rendering translucent pixels can add one rounding stage.
            // A tolerance of 2/255 is used only for the high-DPI alpha case.
            if ( delta > std::max( tolerance, opacity == 1 ? 0 : 1 ) ) ++different;
        }
    if ( different )
        std::cerr << name << ": " << different << " pixels differ; max delta " << maxDifference << '\n';
    check( different == 0, name );
    if ( type == QPaintEngine::Windows && !editor )
    {
        check( device.engine.deviceAligned, "native engine gets identity transform" );
        check( device.engine.maxTilePixels <= 1024*1024, "bounded tile allocation" );
    }
    std::cout << name << ": " << device.engine.calls << " image calls\n";
}

int main( int argc, char** argv )
{
    QCoreApplication app( argc, argv );
    for ( int angle : { 0, 90, 180, 270 } )
        for ( int flip : { 0, 1, 2, 3 } )
        {
            QTransform map;
            map.translate( 180, 180 );
            map.rotate( angle );
            map.scale( flip&1 ? -1 : 1, flip&2 ? -1 : 1 );
            runCase( "right-angle rotation/reflection", map, QSize( 400, 400 ), false, 1, false, false );
        }
    QTransform map;
    map.translate( 180, 180 ); map.rotate( 31 ); map.shear( .15, -.08 ); map.scale( 1.7, 2.3 );
    runCase( "arbitrary rotation/shear", map, QSize( 600, 600 ), false, 1, false, true );
    runCase( "clipping/opacity", map, QSize( 600, 600 ), true, .6, false, true );
    runCase( "viewport/window", map, QSize( 1100, 1100 ), true, 1, true, true );
    QTransform big;
    big.translate( 1450, 1450 ); big.rotate( 180 ); big.scale( 11, 13 );
    runCase( "multiple tiles at high DPI", big, QSize( 1600, 1600 ), true, 1, false, true,
             QPaintEngine::Windows, false, 2 );
    runCase( "preview bypass", map, QSize( 600, 600 ), false, 1, false, true, QPaintEngine::Picture );
    runCase( "raster preview bypass", map, QSize( 600, 600 ), false, 1, false, true, QPaintEngine::Raster );
    runCase( "PDF bypass", map, QSize( 600, 600 ), false, 1, false, true, QPaintEngine::Pdf );
    runCase( "editor bypass", map, QSize( 600, 600 ), false, 1, false, true, QPaintEngine::Windows, true );
    QTransform outside;
    outside.translate( -1000, -1000 );
    runCase( "off-page image", outside, QSize( 400, 400 ), false, 1, false, true );
    return failures ? 1 : 0;
}
"""
TEST_CMAKE = """  # 006: native Windows raster orientation regression (no printer required).
  add_executable (TestWindowsRasterPrint TestWindowsRasterPrint.cpp)
  target_link_libraries (TestWindowsRasterPrint Model Qt6::Gui)
  add_test (NAME WindowsRasterPrint COMMAND TestWindowsRasterPrint)

"""


def patch_source(text):
    if "drawRasterImageWithoutReflectiveTransform" in text:
        raise RuntimeError("old 006 is already applied; use a fresh upstream checkout")
    include = '#include "WindowsRasterPrint.hpp"'
    if include in text:
        if text.count("detail::drawWindowsRasterImage(") != 4:
            raise RuntimeError("006 is only partially applied; use a fresh upstream checkout")
        return text
    anchor = '#include "ModelImageObject.hpp"'
    if text.count(anchor) != 1:
        raise RuntimeError("ModelImageObject include anchor missing or ambiguous")
    for signature in ("void ModelImageObject::drawObject(", "void ModelImageObject::drawShadow("):
        if text.count(signature) != 1:
            raise RuntimeError(f"source function missing or ambiguous: {signature}")
    calls = re.compile(r"painter->drawImage\(\s*destRect\s*,\s*(mImage|image|shadowImage)\s*\);")
    matches = calls.findall(text)
    if sorted(matches) != ["image", "mImage", "shadowImage", "shadowImage"]:
        raise RuntimeError(f"expected fixed/merge raster and two shadow draws; found {matches}")
    text = text.replace(anchor, anchor + "\n" + include, 1)
    return calls.sub(lambda m: "detail::drawWindowsRasterImage( painter, destRect, "
                     + m.group(1) + ", inEditor );", text)


def patch_cmake(text):
    if TEST_CMAKE in text:
        return text
    if "TestWindowsRasterPrint" in text:
        raise RuntimeError("raster test CMake entry differs from 006; refusing to overwrite")
    anchor = "endif (Qt6Test_FOUND)"
    if text.count(anchor) != 1:
        raise RuntimeError("Qt6Test_FOUND CMake anchor missing or ambiguous")
    return text.replace(anchor, TEST_CMAKE + anchor, 1)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", default="src", type=Path)
    parser.add_argument("--check", action="store_true", help="validate without writing")
    args = parser.parse_args()
    root = args.root.resolve()
    edits = []
    # Validate every input and generated file before changing anything.
    for rel, transform in (("model/ModelImageObject.cpp", patch_source),
                           ("model/unit_tests/CMakeLists.txt", patch_cmake)):
        path = root / rel
        if not path.is_file():
            raise RuntimeError(f"missing source file: {path}")
        original = path.read_bytes()
        newline = "\r\n" if b"\r\n" in original else "\n"
        updated = transform(original.decode("utf-8").replace("\r\n", "\n"))
        edits.append((path, original, updated.replace("\n", newline).encode("utf-8")))
    for rel, content in (("model/WindowsRasterPrint.hpp", HEADER),
                         ("model/unit_tests/TestWindowsRasterPrint.cpp", TEST)):
        path = root / rel
        expected = content.encode("utf-8")
        original = path.read_bytes() if path.exists() else None
        if original is not None and original != expected:
            raise RuntimeError(f"generated file differs from 006; refusing to overwrite: {path}")
        edits.append((path, original, expected))
    for path, original, updated in edits:
        rel = path.relative_to(root)
        if original == updated:
            print(f"[skip] {rel}: already applied")
        elif args.check:
            print(f"[check] {rel}: ready")
        else:
            path.write_bytes(updated)
            print(f"[ok] {rel}")
    print("006: validated" if args.check else "006: applied successfully")


if __name__ == "__main__":
    try:
        main()
    except (OSError, UnicodeError, RuntimeError) as error:
        raise SystemExit(f"006: {error}")
